"""Fold placement + per-line word timings into one cue table for the composition.

Each line was padded by a known 300ms before transcription and never resampled
in time, so a word at `t` in the padded file sits at `placed_start + t - 0.3`
on the timeline. That is exact; no stretching, so nothing drifts.
"""
import sys, json, pathlib, re
ROOT = pathlib.Path(sys.argv[1]); PAD = 0.3
spec  = json.loads((ROOT / "lines.json").read_text())
place = json.loads((ROOT / "build/placement.json").read_text())

def norm(w): return re.sub(r"[^a-z0-9]", "", w.lower())

words, lines, warn = {}, {}, []
for ln in spec["lines"]:
    lid = ln["id"]; a, b = place["lines"][lid]
    tx = json.loads((ROOT / f"build/tx/{lid}.json").read_text())["words"]
    ws = [{"w": w["text"], "a": round(a + w["start"] - PAD, 3),
           "b": round(a + w["end"] - PAD, 3)} for w in tx]
    for w in ws:  # Parakeet brackets edges a few frames wide; the track is
        w["a"] = round(max(a, min(w["a"], b)), 3)   # silent outside the placed
        w["b"] = round(max(a, min(w["b"], b)), 3)   # span, so clamp rather than drift.
    if ws and (ws[0]["a"] < a - 0.25 or ws[-1]["b"] > b + 0.25):
        warn.append(f"{lid}: words {ws[0]['a']:.2f}-{ws[-1]['b']:.2f} outside {a:.2f}-{b:.2f}")
    words[lid] = ws

    # Subtitle chunks. Each declares how many transcript words it covers, so
    # every chunk is timed by the words actually spoken under it. lines.json is
    # written only after that count is checked against the transcript, which is
    # why this can index straight in.
    subs, i, out = ln["subs"], 0, []
    if sum(n for _, n in subs) != len(ws):
        raise SystemExit(f"{lid}: subs claim {sum(n for _,n in subs)} of {len(ws)} words")
    for disp, n in subs:
        out.append({"t": disp, "a": ws[i]["a"], "b": ws[i + n - 1]["b"]})
        i += n

    lines[lid] = {"a": a, "b": b, "say": ln["say"], "chunks": out}

js = ROOT / "build/cues.js"
js.write_text(
  "// GENERATED by tools/cues.py - do not edit.\n"
  "window.CUES = " + json.dumps(
      {"total": place["total"], "scenes": place["scenes"], "lines": lines, "words": words},
      indent=1) + ";\n"
  "// at('l03','screenshot') -> the second that word is spoken. Throws if the\n"
  "// word is not in the transcript, so a typo fails the build, not the render.\n"
  "window.at = function (lid, needle, nth) {\n"
  "  var ws = window.CUES.words[lid];\n"
  "  if (!ws) throw new Error('at(): no line ' + lid);\n"
  "  var k = String(needle).toLowerCase().replace(/[^a-z0-9]/g, ''), hit = [];\n"
  "  for (var i = 0; i < ws.length; i++)\n"
  "    if (ws[i].w.toLowerCase().replace(/[^a-z0-9]/g, '') === k) hit.push(ws[i]);\n"
  "  if (!hit.length) throw new Error('at(): \"' + needle + '\" not in ' + lid +\n"
  "    ' — spoken: ' + ws.map(function (w) { return w.w; }).join(' '));\n"
  "  var w = hit[(nth || 1) - 1];\n"
  "  if (!w) throw new Error('at(): ' + lid + ' has ' + hit.length + ' x \"' + needle + '\"');\n"
  "  return w.a;\n"
  "};\n"
  "window.end = function (lid, needle, nth) {\n"
  "  var a = window.at(lid, needle, nth), ws = window.CUES.words[lid];\n"
  "  for (var i = 0; i < ws.length; i++) if (ws[i].a === a) return ws[i].b;\n"
  "  return a;\n"
  "};\n")
nw = sum(len(v) for v in words.values())
nc = sum(len(v["chunks"]) for v in lines.values())
print(f"cues.js  {nw} spoken words, {nc} subtitle chunks, total {place['total']}s")
print("longest chunks:", sorted((len(c['t']) for v in lines.values() for c in v['chunks']))[-4:])
for w in warn: print("  WARN", w)
